-- Seed calendario stagionale (generato da tool/genera_seed_contenuti.py).
-- 12 note (una per mese). Idempotente.
delete from calendario_stagionale;
insert into calendario_stagionale (mese, titolo, testo) values (1, 'Gennaio – Svernanti e prime voci', 'È piena stagione degli uccelli svernanti: cince, pettirossi e fringuelli affollano le mangiatoie, e sui laghi si radunano anatre e folaghe. Nelle giornate miti puoi già sentire le prime cinciallegre "accordare" il canto.');
insert into calendario_stagionale (mese, titolo, testo) values (2, 'Febbraio – Si scaldano le voci', 'Con l''allungarsi delle giornate i residenti iniziano a cantare e a formare le coppie. È anche il periodo in cui i rapaci notturni, come l''allocco, sono più attivi e vocali.');
insert into calendario_stagionale (mese, titolo, testo) values (3, 'Marzo – Tornano i migratori', 'Riparte la migrazione: rondini, balestrucci e luì rientrano dall''Africa e il canto territoriale si fa intenso. È un ottimo mese per annotare i primi arrivi nel tuo territorio.');
insert into calendario_stagionale (mese, titolo, testo) values (4, 'Aprile – Corteggiamenti e primi nidi', 'Migrazione e corteggiamento al culmine: molte specie costruiscono il nido e depongono le prime uova. I maschi cantano a pieno regime per difendere il territorio.');
insert into calendario_stagionale (mese, titolo, testo) values (5, 'Maggio – Piena cova', 'È il cuore della stagione riproduttiva: nidi ovunque e deposizione in pieno svolgimento. Il coro dell''alba raggiunge il massimo, con decine di voci sovrapposte.');
insert into calendario_stagionale (mese, titolo, testo) values (6, 'Giugno – I piccoli lasciano il nido', 'Molti giovani si involano e gli adulti sono indaffarati a nutrirli: vedrai uccelli goffi e chiassosi ai bordi delle siepi. Verso fine mese il canto comincia a calare.');
insert into calendario_stagionale (mese, titolo, testo) values (7, 'Luglio – Silenzio e seconde covate', 'Gli uccelli diventano più discreti: finita gran parte della riproduzione, alcuni tentano una seconda covata e molti iniziano la muta. È un mese più tranquillo, meglio le prime ore del mattino.');
insert into calendario_stagionale (mese, titolo, testo) values (8, 'Agosto – Muta e primi movimenti', 'Periodo di muta e di quiete, ma iniziano i primi spostamenti autunnali: i rondoni, tra i primi a partire, lasciano i cieli delle città. Tieni d''occhio i raduni prima della partenza.');
insert into calendario_stagionale (mese, titolo, testo) values (9, 'Settembre – Grande migrazione autunnale', 'La migrazione verso sud entra nel vivo: coste, zone umide e valichi si riempiono di uccelli di passaggio. È uno dei mesi più spettacolari per chi osserva.');
insert into calendario_stagionale (mese, titolo, testo) values (10, 'Ottobre – Arrivano gli svernanti', 'Mentre gli ultimi migratori scendono a sud, dal nord arrivano tordi, pettirossi e fringuelli che passeranno qui l''inverno. Le zone umide si popolano di anatre e limicoli.');
insert into calendario_stagionale (mese, titolo, testo) values (11, 'Novembre – Si formano i gruppi invernali', 'La migrazione si esaurisce e gli uccelli si organizzano in gruppi per affrontare il freddo. Le mangiatoie tornano importanti: è il momento di riempirle.');
insert into calendario_stagionale (mese, titolo, testo) values (12, 'Dicembre – Inverno pieno', 'Su laghi e zone umide si concentrano anatre, oche e folaghe svernanti, uno degli spettacoli dell''inverno. In giardino, acqua e cibo puliti aiutano gli uccelli nei giorni più rigidi.');
